name: DESTROY Platform

on:
  workflow_dispatch:

jobs:
  run-terraform:
    uses: ./.github/workflows/terraform-destroy.yml
    with:
      working-directory: platform/alz
      tfvar-file: platform.tfvars
    secrets: inherit
